/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package account;
import java.io.File;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import managingstaff.TrackOrder;
import user.ViewAccountDetails;
import deliveryStaff.DStaffViewAccountDetails;
import java.io.FileNotFoundException;
import java.io.IOException;


/**
 *
 * @author kir7
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jlCompName = new javax.swing.JLabel();
        jlLogo = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        tfUname = new javax.swing.JTextField();
        tfPass = new javax.swing.JPasswordField();
        jlUname = new javax.swing.JLabel();
        jlPass = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        btnSignup = new javax.swing.JButton();
        jlIconPass = new javax.swing.JLabel();
        jlIconUser = new javax.swing.JLabel();
        jlDontHaveAcc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setForeground(new java.awt.Color(223, 61, 76));

        jPanel4.setBackground(new java.awt.Color(71, 88, 168));
        jPanel4.setForeground(new java.awt.Color(60, 63, 65));

        jlCompName.setFont(new java.awt.Font("Sora", 1, 24)); // NOI18N
        jlCompName.setText("Way Express");

        jlLogo.setIcon(new javax.swing.ImageIcon("/home/kir7/Documents/BSC-IT/3rdSem/Java/NetBeansProjects/Way-Express/src/main/java/icons/courier.png")); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jlCompName))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jlLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addComponent(jlCompName)
                .addGap(63, 63, 63))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(111, 138, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfUname.setBackground(new java.awt.Color(111, 138, 255));
        tfUname.setFont(new java.awt.Font("Sora", 0, 13)); // NOI18N
        tfUname.setForeground(new java.awt.Color(60, 63, 65));
        tfUname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));
        jPanel5.add(tfUname, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 115, 20));

        tfPass.setBackground(new java.awt.Color(111, 138, 255));
        tfPass.setFont(new java.awt.Font("Sora", 0, 13)); // NOI18N
        tfPass.setForeground(new java.awt.Color(60, 63, 65));
        tfPass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));
        jPanel5.add(tfPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 115, -1));

        jlUname.setFont(new java.awt.Font("Sora", 1, 13)); // NOI18N
        jlUname.setForeground(new java.awt.Color(60, 63, 65));
        jlUname.setText("Username");
        jPanel5.add(jlUname, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, 20));

        jlPass.setFont(new java.awt.Font("Sora", 1, 13)); // NOI18N
        jlPass.setForeground(new java.awt.Color(60, 63, 65));
        jlPass.setText("Password");
        jPanel5.add(jlPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        btnLogin.setBackground(new java.awt.Color(111, 138, 255));
        btnLogin.setFont(new java.awt.Font("Sora", 0, 13)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel5.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        btnSignup.setBackground(new java.awt.Color(111, 138, 255));
        btnSignup.setFont(new java.awt.Font("Sora", 0, 13)); // NOI18N
        btnSignup.setText("Sign Up");
        btnSignup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignupActionPerformed(evt);
            }
        });
        jPanel5.add(btnSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 90, -1));

        jlIconPass.setIcon(new javax.swing.ImageIcon("/home/kir7/Documents/BSC-IT/3rdSem/Java/NetBeansProjects/Way-Express/src/main/java/icons/pass.png")); // NOI18N
        jPanel5.add(jlIconPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 20, 20));

        jlIconUser.setIcon(new javax.swing.ImageIcon("/home/kir7/Documents/BSC-IT/3rdSem/Java/NetBeansProjects/Way-Express/src/main/java/icons/user.png")); // NOI18N
        jPanel5.add(jlIconUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 20, 20));

        jlDontHaveAcc.setFont(new java.awt.Font("Sora", 1, 10)); // NOI18N
        jlDontHaveAcc.setText("Don't have an account?");
        jPanel5.add(jlDontHaveAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, 20));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupActionPerformed
        setVisible(false);
        new Register().setVisible(true);        
    }//GEN-LAST:event_btnSignupActionPerformed

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        try {
            if(verifyLogin() == true){
                JOptionPane.showMessageDialog(this, "Logged in successfully!"); 
            }
            else{
                JOptionPane.showMessageDialog(this, "Username or password incorrect!");                
            }
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLoginMouseClicked

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginActionPerformed

    public boolean verifyLogin() throws FileNotFoundException, IOException{
        File file = new File("user.txt"); // new file instance
        if(!file.exists()){ //creates file if doesnt exist
            file.createNewFile();
        }
        User obj = new User() {};
        Scanner fileReader = new Scanner(file); //scanner instance to read file
        while(fileReader.hasNextLine()){
            String line = fileReader.nextLine();
            String[] value = line.split("_");    //split on "_"
            obj.accType = value[9];
            obj.uname = value[7];
            obj.pass = value[8];

            if(tfUname.getText().equals("admin") && tfPass.getText().equals("admin")){
                    setVisible(false);
                    fileReader.close();
                    new TrackOrder().setVisible(true);  
                    return true;   
            }

            if(tfUname.getText().equals(obj.uname) && tfPass.getText().equals(obj.pass)){
                if (obj.accType.equals("Managing Staff")){
                    setVisible(false);
                    fileReader.close();
                    new TrackOrder().setVisible(true);
                    return true;   
                } 
                else{
                    if (obj.accType.equals("Delivery Staff")){
                        setVisible(false);
                        fileReader.close();
                          new DStaffViewAccountDetails(value[0]).setVisible(true); 
                        return true;   
                    } 
                    else{
                        setVisible(false);
                        fileReader.close();
                        new ViewAccountDetails(value[0]).setVisible(true);
                        return true;
                    }
                }
            }
        }
        fileReader.close();
        return false;
    }
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSignup;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel jlCompName;
    private javax.swing.JLabel jlDontHaveAcc;
    private javax.swing.JLabel jlIconPass;
    private javax.swing.JLabel jlIconUser;
    private javax.swing.JLabel jlLogo;
    private javax.swing.JLabel jlPass;
    private javax.swing.JLabel jlUname;
    private javax.swing.JPasswordField tfPass;
    private javax.swing.JTextField tfUname;
    // End of variables declaration//GEN-END:variables
}
