/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package managingstaff;

import account.Login;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author kir7
 */
public class Appoint extends javax.swing.JFrame {

    /**
     * Creates new form Appoint
     */
       public Appoint() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jbGenerateReport = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jbAppoint = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jbFeedback = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jbLogout = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jbOrder = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jlFullName = new javax.swing.JLabel();
        jlDateformat = new javax.swing.JLabel();
        jlEmail = new javax.swing.JLabel();
        jlGender = new javax.swing.JLabel();
        jlDob = new javax.swing.JLabel();
        jlAddress = new javax.swing.JLabel();
        jlUname = new javax.swing.JLabel();
        jlPhone = new javax.swing.JLabel();
        jlRole = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        tfDOB = new javax.swing.JTextField();
        tfAddress = new javax.swing.JTextField();
        tfUserID = new javax.swing.JTextField();
        tfFullName = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        tfGender = new javax.swing.JTextField();
        tfPhone = new javax.swing.JTextField();
        cbRole = new javax.swing.JComboBox<>();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setForeground(new java.awt.Color(223, 61, 76));

        jPanel4.setBackground(new java.awt.Color(71, 88, 168));
        jPanel4.setForeground(new java.awt.Color(60, 63, 65));

        jLabel3.setFont(new java.awt.Font("Sora", 1, 24)); // NOI18N
        jLabel3.setText("Way Express");

        jPanel6.setBackground(new java.awt.Color(71, 88, 168));
        jPanel6.setPreferredSize(new java.awt.Dimension(0, 38));

        jButton11.setBorder(null);
        jButton11.setBorderPainted(false);
        jButton11.setContentAreaFilled(false);
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton11.setDefaultCapable(false);
        jButton11.setFocusPainted(false);
        jButton11.setFocusable(false);
        jButton11.setMargin(null);
        jButton11.setRequestFocusEnabled(false);
        jButton11.setRolloverEnabled(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(71, 88, 168));

        jbGenerateReport.setFont(new java.awt.Font("Sora", 0, 13)); // NOI18N
        jbGenerateReport.setText("Generate Report");
        jbGenerateReport.setBorder(null);
        jbGenerateReport.setBorderPainted(false);
        jbGenerateReport.setContentAreaFilled(false);
        jbGenerateReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbGenerateReport.setDefaultCapable(false);
        jbGenerateReport.setFocusPainted(false);
        jbGenerateReport.setFocusable(false);
        jbGenerateReport.setMargin(null);
        jbGenerateReport.setRequestFocusEnabled(false);
        jbGenerateReport.setRolloverEnabled(false);
        jbGenerateReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGenerateReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbGenerateReport, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jbGenerateReport, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel11.setBackground(new java.awt.Color(111, 138, 255));

        jbAppoint.setBackground(new java.awt.Color(111, 138, 255));
        jbAppoint.setFont(new java.awt.Font("Sora", 0, 13)); // NOI18N
        jbAppoint.setText("Account Management");
        jbAppoint.setBorder(null);
        jbAppoint.setBorderPainted(false);
        jbAppoint.setContentAreaFilled(false);
        jbAppoint.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbAppoint.setDefaultCapable(false);
        jbAppoint.setFocusPainted(false);
        jbAppoint.setFocusable(false);
        jbAppoint.setMargin(null);
        jbAppoint.setRequestFocusEnabled(false);
        jbAppoint.setRolloverEnabled(false);
        jbAppoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAppointActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbAppoint, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jbAppoint, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel12.setBackground(new java.awt.Color(71, 88, 168));

        jbFeedback.setFont(new java.awt.Font("Sora", 0, 13)); // NOI18N
        jbFeedback.setText("Feedback");
        jbFeedback.setBorder(null);
        jbFeedback.setBorderPainted(false);
        jbFeedback.setContentAreaFilled(false);
        jbFeedback.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbFeedback.setDefaultCapable(false);
        jbFeedback.setFocusPainted(false);
        jbFeedback.setFocusable(false);
        jbFeedback.setMargin(null);
        jbFeedback.setRequestFocusEnabled(false);
        jbFeedback.setRolloverEnabled(false);
        jbFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFeedbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jbFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel13.setBackground(new java.awt.Color(71, 88, 168));
        jPanel13.setPreferredSize(new java.awt.Dimension(0, 38));

        jbLogout.setFont(new java.awt.Font("Sora", 0, 13)); // NOI18N
        jbLogout.setText("Logout");
        jbLogout.setBorder(null);
        jbLogout.setBorderPainted(false);
        jbLogout.setContentAreaFilled(false);
        jbLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbLogout.setDefaultCapable(false);
        jbLogout.setFocusPainted(false);
        jbLogout.setFocusable(false);
        jbLogout.setMargin(null);
        jbLogout.setRequestFocusEnabled(false);
        jbLogout.setRolloverEnabled(false);
        jbLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jbLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel14.setBackground(new java.awt.Color(71, 88, 168));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        jPanel15.setBackground(new java.awt.Color(71, 88, 168));

        jbOrder.setFont(new java.awt.Font("Sora", 0, 13)); // NOI18N
        jbOrder.setText("Order");
        jbOrder.setBorder(null);
        jbOrder.setBorderPainted(false);
        jbOrder.setContentAreaFilled(false);
        jbOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbOrder.setDefaultCapable(false);
        jbOrder.setFocusPainted(false);
        jbOrder.setFocusable(false);
        jbOrder.setMargin(null);
        jbOrder.setRequestFocusEnabled(false);
        jbOrder.setRolloverEnabled(false);
        jbOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(jbOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(26, 26, 26))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addGap(40, 40, 40)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel5)
                .addGap(0, 0, 0)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(199, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(111, 138, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jlFullName.setFont(new java.awt.Font("Sora", 0, 13)); // NOI18N
        jlFullName.setForeground(new java.awt.Color(60, 63, 65));
        jlFullName.setText("Full Name");
        jPanel5.add(jlFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        jlDateformat.setFont(new java.awt.Font("Sora", 0, 8)); // NOI18N
        jlDateformat.setText("( dd-mm-yyyy)");
        jPanel5.add(jlDateformat, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        jlEmail.setFont(new java.awt.Font("Sora", 0, 13)); // NOI18N
        jlEmail.setForeground(new java.awt.Color(60, 63, 65));
        jlEmail.setText("Email");
        jPanel5.add(jlEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        jlGender.setFont(new java.awt.Font("Sora", 0, 13)); // NOI18N
        jlGender.setForeground(new java.awt.Color(60, 63, 65));
        jlGender.setText("Gender");
        jPanel5.add(jlGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        jlDob.setFont(new java.awt.Font("Sora", 0, 13)); // NOI18N
        jlDob.setForeground(new java.awt.Color(60, 63, 65));
        jlDob.setText("Date of Birth");
        jPanel5.add(jlDob, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        jlAddress.setFont(new java.awt.Font("Sora", 0, 13)); // NOI18N
        jlAddress.setForeground(new java.awt.Color(60, 63, 65));
        jlAddress.setText("Address");
        jPanel5.add(jlAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        jlUname.setFont(new java.awt.Font("Sora", 0, 13)); // NOI18N
        jlUname.setForeground(new java.awt.Color(60, 63, 65));
        jlUname.setText("Username");
        jPanel5.add(jlUname, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        jlPhone.setFont(new java.awt.Font("Sora", 0, 13)); // NOI18N
        jlPhone.setForeground(new java.awt.Color(60, 63, 65));
        jlPhone.setText("Phone");
        jPanel5.add(jlPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, -1));

        jlRole.setFont(new java.awt.Font("Sora", 0, 13)); // NOI18N
        jlRole.setForeground(new java.awt.Color(60, 63, 65));
        jlRole.setText("Role");
        jPanel5.add(jlRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, -1, -1));

        btnSubmit.setBackground(new java.awt.Color(111, 138, 255));
        btnSubmit.setFont(new java.awt.Font("Sora", 0, 13)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        jPanel5.add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 490, -1, -1));

        tfDOB.setEditable(false);
        tfDOB.setFont(new java.awt.Font("Sora", 0, 13)); // NOI18N
        jPanel5.add(tfDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 180, -1));

        tfAddress.setEditable(false);
        tfAddress.setFont(new java.awt.Font("Sora", 0, 13)); // NOI18N
        jPanel5.add(tfAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 180, -1));

        tfUserID.setFont(new java.awt.Font("Sora", 0, 13)); // NOI18N
        jPanel5.add(tfUserID, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 180, -1));

        tfFullName.setEditable(false);
        tfFullName.setFont(new java.awt.Font("Sora", 0, 13)); // NOI18N
        jPanel5.add(tfFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 180, -1));

        tfEmail.setEditable(false);
        tfEmail.setFont(new java.awt.Font("Sora", 0, 13)); // NOI18N
        jPanel5.add(tfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 180, -1));

        tfGender.setEditable(false);
        tfGender.setFont(new java.awt.Font("Sora", 0, 13)); // NOI18N
        jPanel5.add(tfGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 180, -1));

        tfPhone.setEditable(false);
        tfPhone.setFont(new java.awt.Font("Sora", 0, 13)); // NOI18N
        jPanel5.add(tfPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 180, -1));

        cbRole.setFont(new java.awt.Font("Sora", 0, 13)); // NOI18N
        cbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select the role", "User", "Delivery Staff", "Managing Staff" }));
        jPanel5.add(cbRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 180, -1));

        btnSearch.setIcon(new javax.swing.ImageIcon("/home/kir7/Documents/BSC-IT/3rdSem/Java/NetBeansProjects/Way-Express/src/main/java/icons/search.png")); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel5.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, -1, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Note:\nEnter the User ID and click the\n'Search' button to get the user \ndetails.\nCheck if that is the user you want\nto promote/demote.\nChange the role of the user using\nthe Combo Box and hit Submit button.");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 280, 180));

        jLabel1.setFont(new java.awt.Font("Sora", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(60, 63, 65));
        jLabel1.setText("User ID");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        tfUsername.setEditable(false);
        tfUsername.setFont(new java.awt.Font("Sora", 0, 13)); // NOI18N
        jPanel5.add(tfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 180, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 783, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jbGenerateReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGenerateReportActionPerformed
        setVisible(false);
        new ReportManagement().setVisible(true);
    }//GEN-LAST:event_jbGenerateReportActionPerformed

    private void jbAppointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAppointActionPerformed
        
    }//GEN-LAST:event_jbAppointActionPerformed

    private void jbFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFeedbackActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new FeedbackTableView().setVisible(true);
    }//GEN-LAST:event_jbFeedbackActionPerformed

    private void jbLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLogoutActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_jbLogoutActionPerformed

    private void jbOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOrderActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new PlaceOrder().setVisible(true);
    }//GEN-LAST:event_jbOrderActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        try {
            assignRole();
        } catch (IOException ex) {
            Logger.getLogger(Appoint.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
    
        File file = new File("user.txt"); // new file instance

        Scanner fileReader = null;
        try {
            fileReader = new Scanner(file); //scanner instance to read file
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Appoint.class.getName()).log(Level.SEVERE, null, ex);
        }

        while(fileReader.hasNextLine()){
            String line = fileReader.nextLine();
            String[] value = line.split("_");    //split on "_"
            if(value[0].equals(tfUserID.getText())){
                tfUsername.setText(value[7]);
                tfFullName.setText(value[1]);
                tfEmail.setText(value[2]);
                tfGender.setText(value[4]);
                tfDOB.setText(value[5]);
                tfPhone.setText(value[3]);
                tfAddress.setText(value[6]);
            }
        }
        fileReader.close();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void assignRole() throws IOException{
        File tempFile = new File("temp.txt");
        File oldFile = new File("user.txt");

        Scanner fileReader = new Scanner(oldFile);
        FileWriter fw = new FileWriter(tempFile,true);
        BufferedWriter bw = new BufferedWriter(fw);
        PrintWriter pw = new PrintWriter(bw);

        if(cbRole.getSelectedItem().equals("Select the role")){
            JOptionPane.showMessageDialog(this, "Select a role!");
        }
        else{
            while(fileReader.hasNextLine()){
            String line = fileReader.nextLine();
            String[] value = line.split("_");    //split on "_"
            
            if(value[0].equals(tfUserID.getText())){
                System.out.println("Matches!");
                pw.println(value[0]+"_"+value[1]+"_"+value[2]+"_"+value[3]+"_"+value[4]+"_"+value[5]+"_"+value[6]+"_"+value[7]+"_"+value[8]+"_"+cbRole.getSelectedItem());
                JOptionPane.showMessageDialog(this, "Updated successfully!");
            }

            else{
                System.out.println("Doesn't match");
                pw.println(value[0]+"_"+value[1]+"_"+value[2]+"_"+value[3]+"_"+value[4]+"_"+value[5]+"_"+value[6]+"_"+value[7]+"_"+value[8]+"_"+value[9]);
            }
        }
        fileReader.close();
        pw.flush();
        pw.close();
        bw.close();
        fw.close();
        oldFile.delete();// deletes user.txt
        tempFile.renameTo(oldFile);// renames temp.txt to user.txt   
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Appoint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Appoint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Appoint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Appoint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Appoint().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cbRole;
    private javax.swing.JButton jButton11;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jbAppoint;
    private javax.swing.JButton jbFeedback;
    private javax.swing.JButton jbGenerateReport;
    private javax.swing.JButton jbLogout;
    private javax.swing.JButton jbOrder;
    private javax.swing.JLabel jlAddress;
    private javax.swing.JLabel jlDateformat;
    private javax.swing.JLabel jlDob;
    private javax.swing.JLabel jlEmail;
    private javax.swing.JLabel jlFullName;
    private javax.swing.JLabel jlGender;
    private javax.swing.JLabel jlPhone;
    private javax.swing.JLabel jlRole;
    private javax.swing.JLabel jlUname;
    private javax.swing.JTextField tfAddress;
    private javax.swing.JTextField tfDOB;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfFullName;
    private javax.swing.JTextField tfGender;
    private javax.swing.JTextField tfPhone;
    private javax.swing.JTextField tfUserID;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
